trigger:
- master
- develop

variables:
  packageBasename: 'descript-gstreamer'
  packageId: '$(Build.BuildNumber)'
  hostCores: 2

jobs:

- job: MacOS

  pool:
    vmImage: 'macOS-10.13'

  variables:
    packageName: $(packageBaseName)-mac-$(packageId)

  steps:

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: ./cerbero-uninstalled bootstrap -y
    displayName: Boostrapping cerbero

  - script: ./cerbero-uninstalled package gstreamer-1.0
    displayName: Building package gstreamer-1.0

  - script: mkdir $(packageName)
    displayName: Creating package $(packageName)

- job: Windows

  pool:
    # Windows can be cross-compiled from Linux
    vmImage: 'ubuntu-16.04'

  variables:
    packageName: $(packageBaseName)-win-$(packageId)

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: ./cerbero-uninstalled -c config/cross-win64.cbc bootstrap -y
    displayName: Boostrapping cerbero

  - script: ./cerbero-uninstalled -c config/cross-win64.cbc package gstreamer-1.0
    displayName: Building package gstreamer-1.0

  - script: ls
    displayName: Show contents

  - script: mkdir $(packageName)
    displayName: Creating package $(packageName)

- job: Linux

  pool:
    vmImage: 'ubuntu-16.04'

  variables:
    packageName: $(packageBaseName)-linux-$(packageId)

  steps:

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: ./cerbero-uninstalled bootstrap -y
    displayName: Boostrapping cerbero

  - script: ./cerbero-uninstalled package gstreamer-1.0
    displayName: Building package gstreamer-1.0

  - script: ls
    displayName: Show contents

  - script: mkdir $(packageName)
    displayName: Creating package $(packageName)

