trigger:
- master
- develop

variables:
  packageBasename: 'descript-gstreamer'
  hostCores: 2

jobs:

- job: MacOS

  pool:
    vmImage: 'macOS-10.13'

  variables:
    packageArch: 'mac'

  steps:

  - script: echo "##vso[task.setvariable variable=packageVersion]`cat descript/descript-package-version`"
    displayName: Set the package $(packageBasename)-$(packageArch) version

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: ./cerbero-uninstalled bootstrap -y
    displayName: Boostrapping cerbero

  - script: ./cerbero-uninstalled package gstreamer-1.0
    displayName: Building package gstreamer-1.0

  - script: mkdir $(packageBaseName)-$(packageArch)-$(packageVersion)
    displayName: Creating package $(packageBaseName)-$(packageArch)-$(packageVersion)

- job: Windows

  pool:
    vmImage: 'VS2017-Win2016'

  variables:
    packageArch: 'win'

  steps:

  - script: |
      type descript\descript-package-version
      set /p ENV_APP_VERSION= < descript\descript-package-version
      @echo ##vso[task.setvariable variable=appVersion]%ENV_APP_VERSION%
    displayName: Set the package $(packageBasename)-$(packageArch) version to $(packageVersion)


- job: Linux

  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - script: echo "##vso[task.setvariable variable=packageVersion]`cat descript/descript-package-version`"
    displayName: Set the package $(packageBasename)-$(packageArch) version to $(packageVersion)

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

